FROM --platform=linux/amd64 docker.io/eclipse-temurin:17-jre-jammy

RUN apt-get update && \
    apt-get install -y --no-install-recommends bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir -p \
    /app/data/projects \
    /app/configurations \
    /app/logs

COPY ci-artifact/app.jar /app/app.jar
COPY docker-entrypoint.sh /app/docker-entrypoint.sh

ENV DATA_DIRECTORY="/app/data" \
    CONFIG_PATH="/app/configurations/configuration.xml" \
    LOGBACK_CONFIG_PATH="/app/configurations/logback.xml" \
    PROJECT_WATCH_INTERVAL_SECONDS="1" \
    PROJECT_INITIAL_REVISION_TIMEOUT_SECONDS="60" \
    PROJECT_STARTUP_TIMEOUT_SECONDS="60" \
    PROJECT_SHUTDOWN_TIMEOUT_SECONDS="180"

ENTRYPOINT ["/bin/bash", "/app/docker-entrypoint.sh"]
